
name: build
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.2, 2.3, 2.4, 2.5, 2.6, 3.0]
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test and generate coverage
        run: bin/test
      - name: Format coverage
        if: ${{ matrix.ruby >= 3 }}
        run: bin/prepare_coverage
      - uses: paambaati/codeclimate-action@v2.7.5
        if: ${{ matrix.ruby >= 3 }}
        env:
          CC_TEST_REPORTER_ID: 64c916cd62a6cd844907864a76f17603e6ce48eeff9a3e55f2d85f80a7c6ce6e
        with:
          debug: true
          coverageLocations: coverage/.resultset.json:simplecov
